include:
  - project: tools/templates
    ref: dev
    file:
      - resources/workflow.yml
      - resources/registry.yml

  - component: $CI_SERVER_FQDN/tools/templates/gorelease@dev

stages:
  - release
