/*
Aggr aggregates and unpacks files from directories.

A command-line utility that recursively aggregates files from specified paths into a single file
and unpacks them back to their original directory structure.

Usage:

	aggr [command] [flags]

Use "aggr --help" for more information.
*/
package main

import (
	"fmt"
	"os"

	"github.com/idelchi/aggr/internal/cli"
)

// version is the application version injected at build time.
var version = "unknown - unofficial & generated by unknown"

// main is the entry point of the application.
func main() {
	if err := cli.Execute(version); err != nil {
		fmt.Fprintln(os.Stderr, err)

		os.Exit(1)
	}

	os.Exit(0)
}
