// Package main provides the aggr command-line tool for aggregating and unpacking files.
//
// The aggr tool recursively aggregates files from specified paths into a single file
// and can unpack them back to their original directory structure. It supports
// various filtering options including file size limits, ignore patterns, and
// file type filtering.
package main

import (
	"fmt"
	"os"

	"gitlab.garfield-labs.com/apps/aggr/internal/cli"
)

// version is the application version injected at build time.
var version = "unknown - unofficial & generated by unknown"

// File represents a file path as a string.
type File string

// Files represents a collection of file paths.
type Files []File

// main is the entry point of the application.
func main() {
	if err := cli.Execute(version); err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}
}
